// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRcLFMStQQ7Eyqfop-o8ya0RzJ4rFF-k',
    appId: '1:587968837537:web:06993789a7a1e35939fde0',
    messagingSenderId: '587968837537',
    projectId: 'whatzap2-87ec8',
    authDomain: 'whatzap2-87ec8.firebaseapp.com',
    databaseURL: 'https://whatzap2-87ec8-default-rtdb.firebaseio.com',
    storageBucket: 'whatzap2-87ec8.appspot.com',
    measurementId: 'G-127RK02TTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5e1sYurf-bszNNPOqAskZ1C-YNZIsloE',
    appId: '1:587968837537:android:a45b5093984dc75839fde0',
    messagingSenderId: '587968837537',
    projectId: 'whatzap2-87ec8',
    databaseURL: 'https://whatzap2-87ec8-default-rtdb.firebaseio.com',
    storageBucket: 'whatzap2-87ec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrzt3OeI7pIyl7vLV3riEIALf1unPDUc',
    appId: '1:587968837537:ios:95062ece27de1c2b39fde0',
    messagingSenderId: '587968837537',
    projectId: 'whatzap2-87ec8',
    databaseURL: 'https://whatzap2-87ec8-default-rtdb.firebaseio.com',
    storageBucket: 'whatzap2-87ec8.appspot.com',
    iosClientId: '587968837537-96sfq6ovmbi4depuhnsa0qqtq35tenea.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatzap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrzt3OeI7pIyl7vLV3riEIALf1unPDUc',
    appId: '1:587968837537:ios:95062ece27de1c2b39fde0',
    messagingSenderId: '587968837537',
    projectId: 'whatzap2-87ec8',
    databaseURL: 'https://whatzap2-87ec8-default-rtdb.firebaseio.com',
    storageBucket: 'whatzap2-87ec8.appspot.com',
    iosClientId: '587968837537-96sfq6ovmbi4depuhnsa0qqtq35tenea.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatzap2',
  );
}
