// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8USZSuyLb2ZPbfvoufqZseiq5N0974sg',
    appId: '1:305977578392:web:6de1fb519cafdb68c951ed',
    messagingSenderId: '305977578392',
    projectId: 'whatzap-48a4c',
    authDomain: 'whatzap-48a4c.firebaseapp.com',
    storageBucket: 'whatzap-48a4c.appspot.com',
    measurementId: 'G-S594Z2P3CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfKDFTRJ4GlURZDgVKpvRGDYrjWD8HAc',
    appId: '1:305977578392:android:ebe046e74523ae3cc951ed',
    messagingSenderId: '305977578392',
    projectId: 'whatzap-48a4c',
    storageBucket: 'whatzap-48a4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqkZgDNujlet_XS_b6ZLgNuoFgIU1XzU',
    appId: '1:305977578392:ios:b4f2d1d0f5dc6433c951ed',
    messagingSenderId: '305977578392',
    projectId: 'whatzap-48a4c',
    storageBucket: 'whatzap-48a4c.appspot.com',
    iosClientId: '305977578392-ombcm8tg3hsoda75haatf8csm4ml1hea.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatzap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqkZgDNujlet_XS_b6ZLgNuoFgIU1XzU',
    appId: '1:305977578392:ios:b4f2d1d0f5dc6433c951ed',
    messagingSenderId: '305977578392',
    projectId: 'whatzap-48a4c',
    storageBucket: 'whatzap-48a4c.appspot.com',
    iosClientId: '305977578392-ombcm8tg3hsoda75haatf8csm4ml1hea.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatzap',
  );
}
